<?php

/**
 * @file
 * This is the Media Download All module.
 */

use Drupal\Core\Cache\CacheBackendInterface;
use Drupal\Core\Url;
use Drupal\media_download_all\Plugin\Archiver\Zip;

/**
 * Batch operation callback.
 *
 * @param string $file_path
 *   The file patch.
 * @param string $entity_type
 *   The entity type.
 * @param mixed $entity_id
 *   The entity id.
 * @param string $field_name
 *   The field name.
 * @param mixed $fid
 *   The file id.
 * @param mixed $file_name
 *   The file name.
 * @param array $context
 *   The context.
 *
 * @throws \Drupal\Core\Archiver\ArchiverException
 */
function media_download_all_operation($file_path, $entity_type, $entity_id, $field_name, $fid, $file_name, array &$context) {
  $file_zip = new Zip($file_path, TRUE);
  $file_zip->add($fid);
  $file_zip->close();

  $context['results'][] = [$file_path, $entity_type, $entity_id, $field_name];
  $context['message'] = t('Compressing file @fid - @file_name...',
    ['@fid' => $fid, '@file_name' => $file_name]);
}

/**
 * Batch finished callback.
 *
 * @param bool $success
 *   Was the process successful?
 * @param array $results
 *   Batch process results array.
 * @param array $operations
 *   Performed operations array.
 */
function media_download_all_operation_finished($success, array $results, array $operations) {
  $messenger = \Drupal::messenger();
  $cache_bin = \Drupal::cache();

  if ($success) {

    if (count($results)) {

      list($file_path, $entity_type, $entity_id, $field_name) = reset($results);

      $cid = 'media_download_all:' . $entity_type . ':' . $entity_id;
      $cache = $cache_bin->get($cid);
      if ($cache) {
        $cached_files = $cache->data;
      }

      $cached_files[$field_name] = $file_path;
      $cache_tags = ['media_download_all', "{$entity_type}:{$entity_id}"];
      $cache_bin->set($cid, $cached_files, CacheBackendInterface::CACHE_PERMANENT, $cache_tags);

      $url = Url::fromRoute('media_download_all.download_path', [
        'entity_type' => $entity_type,
        'entity_id' => $entity_id,
        'field_name' => $field_name,
      ])->toString();

      $messenger->addMessage(t('Click <a href="@url"><b>here</b></a> to download all <b>@count</b> files compressed in a <b>zip</b> file.', ['@url' => $url, '@count' => count($results)]));

    }
  }
  else {
    $messenger->addError(t('Finished with an error.'));
  }
}
